version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing Something...."
  pre_build:
    commands:
      - echo "Pre-Build Something...."
  build:
    commands:
      - echo "We Will Check Something....."
      - echo "The test is Runing...."
      - grep -Fq "Congratulations" index.html
  post_build:
    commands:
      - echo "We already finisih..."
